# Generated by Django 4.1 on 2023-03-04 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=20, verbose_name="Telegram ID"),
                ),
            ],
            options={
                "verbose_name": "Profile of User",
                "verbose_name_plural": "Profiles of Users",
            },
        ),
    ]
