# Generated by Django 4.1 on 2023-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telegram ID"
            ),
        ),
    ]
