# Generated by Django 4.1 on 2023-03-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_corporate_account",
            field=models.BooleanField(default=False, verbose_name="Corporate account"),
        ),
    ]
