version: '3.9'

services:

  db:
    restart: always
    image: postgres:13.4-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data-call:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres-data-call:

