# Generated by Django 4.1 on 2023-03-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=16, primary_key=True, serialize=False, verbose_name="Code"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                (
                    "sort",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Sorting"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activity Status")),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.RemoveField(
            model_name="organization",
            name="employees",
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(default=django.utils.timezone.now, verbose_name="Date joined"),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_info",
                        to="organizations.organization",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="employees",
                        to="organizations.position",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisations_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee organization",
                "verbose_name_plural": "Employee organizations",
                "ordering": ("-date_joined",),
                "unique_together": {("organisation", "user")},
            },
        ),
    ]
