# Generated by Django 4.1 on 2023-03-06 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_alter_profile_telegram_id"),
        ("organizations", "0002_position_remove_organization_employees_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations_employees",
                through="organizations.Employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employees",
            ),
        ),
    ]
