# Generated by Django 4.1 on 2023-03-07 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="employees",
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(default=django.utils.timezone.now, verbose_name="Date joined"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups_info",
                        to="organizations.employee",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members_info",
                        to="organizations.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Band member",
                "verbose_name_plural": "Band members",
                "ordering": ("-date_joined",),
                "unique_together": {("group", "employee")},
            },
        ),
    ]
