# Generated by Django 4.1 on 2023-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_remove_group_employees_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups_members",
                through="organizations.Member",
                to="organizations.employee",
                verbose_name="Band members",
            ),
        ),
    ]
