# Generated by Django 4.1 on 2023-03-07 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_group_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="break_end",
        ),
        migrations.RemoveField(
            model_name="group",
            name="break_max_duration",
        ),
        migrations.RemoveField(
            model_name="group",
            name="break_start",
        ),
        migrations.RemoveField(
            model_name="group",
            name="min_active",
        ),
    ]
