# Generated by Django 4.1 on 2023-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Break",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("break_start", models.TimeField(blank=True, null=True, verbose_name="Start break")),
                ("break_end", models.TimeField(blank=True, null=True, verbose_name="End break")),
            ],
            options={
                "verbose_name": "Lunch break",
                "verbose_name_plural": "Lunch breaks",
                "ordering": ("-replacement__date", "break_start"),
            },
        ),
        migrations.CreateModel(
            name="BreakStatus",
            fields=[
                ("code", models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name="Code")),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("sort", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Sorting")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activity Status")),
            ],
            options={
                "verbose_name": "Break Status",
                "verbose_name_plural": "Breaks Status",
            },
        ),
    ]
