# Generated by Django 4.1 on 2023-02-26 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="organization_directors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Director",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organization_employees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organiztion",
                "verbose_name_plural": "Organizations",
                "ordering": ("name",),
            },
        ),
    ]
