# Generated by Django 4.1 on 2023-02-26 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("breaks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "min_active",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Min count active employees"
                    ),
                ),
                (
                    "break_start",
                    models.TimeField(blank=True, null=True, verbose_name="Start break"),
                ),
                (
                    "break_end",
                    models.TimeField(blank=True, null=True, verbose_name="End break"),
                ),
                (
                    "break_max_duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Max duration of break"
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_employees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employees",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="group_managers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="breaks.organization",
                        verbose_name="Organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ("name",),
            },
        ),
    ]
