# Generated by Django 4.1 on 2023-04-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("breaks", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupInfo",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="breaks_info",
                        serialize=False,
                        to="organisations.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "min_active",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Min count active employees"),
                ),
                ("break_start", models.TimeField(blank=True, null=True, verbose_name="Start break")),
                ("break_end", models.TimeField(blank=True, null=True, verbose_name="End break")),
                (
                    "break_max_duration",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Max duration of break"),
                ),
            ],
            options={
                "verbose_name": "Parameter Launch Break",
                "verbose_name_plural": "Parameter Launch Break",
            },
        ),
        migrations.CreateModel(
            name="Replacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date of replacement")),
                ("break_start", models.TimeField(verbose_name="Start break")),
                ("break_end", models.TimeField(verbose_name="End break")),
                ("break_max_duration", models.PositiveSmallIntegerField(verbose_name="Max time of duration break")),
                (
                    "min_active",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Min. number of active employees"
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement",
                "verbose_name_plural": "Replacements",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="ReplacementEmployee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Replacement - Employees",
                "verbose_name_plural": "Replacements - Employees",
            },
        ),
        migrations.CreateModel(
            name="ReplacementStatus",
            fields=[
                ("code", models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name="Code")),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("sort", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Sorting")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activity Status")),
            ],
            options={
                "verbose_name": "Replacement Status",
                "verbose_name_plural": "Replacements Status",
            },
        ),
        migrations.CreateModel(
            name="ReplacementMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "time_online",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Started shift"),
                ),
                (
                    "time_offline",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Finished my shift"),
                ),
                (
                    "time_break_start",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Gone for lunch"),
                ),
                (
                    "time_break_end",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Came back from lunch"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacements_info",
                        to="organisations.member",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members_info",
                        to="breaks.replacement",
                        verbose_name="Смена",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="members",
                        to="breaks.replacementstatus",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change - group member",
                "verbose_name_plural": "Changes - group members",
            },
        ),
    ]
