# Generated by Django 4.1 on 2023-02-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("breaks", "0002_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("name",),
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.CreateModel(
            name="Replacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date of replacement")),
                ("break_start", models.TimeField(verbose_name="Start break")),
                ("break_end", models.TimeField(verbose_name="End break")),
                (
                    "break_max_duration",
                    models.PositiveSmallIntegerField(
                        verbose_name="Max time of duration break"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacements",
                        to="breaks.group",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement",
                "verbose_name_plural": "Replacements",
                "ordering": ("-date",),
            },
        ),
    ]
