# Generated by Django 4.1 on 2023-04-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("breaks", "0002_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacementemployee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employees",
            ),
        ),
        migrations.AddField(
            model_name="replacementemployee",
            name="replacement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="breaks.replacement",
                verbose_name="Replacement",
            ),
        ),
        migrations.AddField(
            model_name="replacementemployee",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacement_employees",
                to="breaks.replacementstatus",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="replacement",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to="breaks.groupinfo",
                verbose_name="Group",
            ),
        ),
        migrations.AddField(
            model_name="replacement",
            name="members",
            field=models.ManyToManyField(
                related_name="replacements",
                through="breaks.ReplacementMember",
                to="organisations.member",
                verbose_name="Shift members",
            ),
        ),
        migrations.AddField(
            model_name="break",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breaks",
                to="breaks.replacementmember",
                verbose_name="Shift member",
            ),
        ),
        migrations.AddField(
            model_name="break",
            name="replacement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breaks",
                to="breaks.replacement",
                verbose_name="Replacement",
            ),
        ),
        migrations.AddField(
            model_name="break",
            name="status",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="breaks",
                to="breaks.breakstatus",
                verbose_name="Status",
            ),
        ),
    ]
