# Generated by Django 4.1 on 2023-02-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("breaks", "0005_replacementemployee"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakStatus",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                (
                    "sort",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Sorting"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Activity Status"),
                ),
            ],
            options={
                "verbose_name": "Replacement Break",
                "verbose_name_plural": "Replacements Break",
            },
        ),
        migrations.AlterModelOptions(
            name="replacementstatus",
            options={
                "verbose_name": "Replacement Status",
                "verbose_name_plural": "Replacements Status",
            },
        ),
    ]
