# Generated by Django 4.1 on 2023-02-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("breaks", "0006_breakstatus_alter_replacementstatus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "break_start",
                    models.TimeField(blank=True, null=True, verbose_name="Start break"),
                ),
                (
                    "break_end",
                    models.TimeField(blank=True, null=True, verbose_name="End break"),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Duration of break"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employees",
                    ),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="breaks.replacement",
                        verbose_name="Replacement",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="breaks",
                        to="breaks.breakstatus",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Break",
                "verbose_name_plural": "Breaks",
                "ordering": ("-replacement__date", "break_start"),
            },
        ),
    ]
