# Generated by Django 4.1 on 2023-02-27 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("breaks", "0007_break"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="break",
            options={
                "ordering": ("-replacement__date", "break_start"),
                "verbose_name": "Lunch break",
                "verbose_name_plural": "Lunch breaks",
            },
        ),
    ]
