# Generated by Django 4.1 on 2023-02-27 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("breaks", "0008_alter_break_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="break",
            name="duration",
        ),
    ]
