# Generated by Django 4.1 on 2023-03-04 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("breaks", "0010_alter_break_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breakstatus",
            options={
                "verbose_name": "Break Status",
                "verbose_name_plural": "Breaks Status",
            },
        ),
    ]
