# Generated by Django 4.1 on 2023-03-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("breaks", "0011_alter_breakstatus_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="director",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="employees",
        ),
        migrations.AlterField(
            model_name="replacement",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to="organizations.group",
                verbose_name="Group",
            ),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
