# Generated by Django 4.1 on 2023-03-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_remove_group_break_end_and_more"),
        ("breaks", "0012_remove_organization_director_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupInfo",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="breaks_info",
                        serialize=False,
                        to="organizations.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "min_active",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Min count active employees"
                    ),
                ),
                ("break_start", models.TimeField(blank=True, null=True, verbose_name="Start break")),
                ("break_end", models.TimeField(blank=True, null=True, verbose_name="End break")),
                (
                    "break_max_duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Max duration of break"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Launch Break",
                "verbose_name_plural": "Parameter Launch Break",
            },
        ),
        migrations.AlterField(
            model_name="replacement",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to="breaks.groupinfo",
                verbose_name="Group",
            ),
        ),
    ]
