# Generated by Django 4.1 on 2023-04-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_offer"),
        ("breaks", "0013_groupinfo_alter_replacement_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplacementMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "time_online",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Начал смену"),
                ),
                (
                    "time_offline",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Закончил смену"),
                ),
                (
                    "time_break_start",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Ушел на обед"),
                ),
                (
                    "time_break_end",
                    models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Вернулся с обеда"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacements_info",
                        to="organizations.member",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена - участник группы",
                "verbose_name_plural": "Смены - участники группы",
            },
        ),
        migrations.AddField(
            model_name="replacement",
            name="members",
            field=models.ManyToManyField(
                related_name="replacements",
                through="breaks.ReplacementMember",
                to="organizations.member",
                verbose_name="Shift members",
            ),
        ),
        migrations.AddField(
            model_name="replacement",
            name="min_active",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Min. number of active employees"
            ),
        ),
        migrations.AddField(
            model_name="replacementmember",
            name="replacement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members_info",
                to="breaks.replacement",
                verbose_name="Смена",
            ),
        ),
        migrations.AddField(
            model_name="replacementmember",
            name="status",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="members",
                to="breaks.replacementstatus",
                verbose_name="Статус",
            ),
        ),
    ]
