# Generated by Django 4.1 on 2023-04-02 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_joined", models.DateField(default=django.utils.timezone.now, verbose_name="Date joined")),
            ],
            options={
                "verbose_name": "Employee organisation",
                "verbose_name_plural": "Employee organisations",
                "ordering": ("-date_joined",),
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(null=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(null=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_joined", models.DateField(default=django.utils.timezone.now, verbose_name="Date joined")),
            ],
            options={
                "verbose_name": "Band member",
                "verbose_name_plural": "Band members",
                "ordering": ("-date_joined",),
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(null=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(null=True, verbose_name="Updated at")),
                ("org_accept", models.BooleanField(blank=True, null=True, verbose_name="Organisation Consent")),
                ("user_accept", models.BooleanField(blank=True, null=True, verbose_name="User Consent")),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(null=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(null=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("code", models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name="Code")),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("sort", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Sorting")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activity Status")),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
    ]
