# Generated by Django 4.1 on 2023-04-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="organisations_directors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Director",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisations_employees",
                through="organisations.Employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employees",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="offers",
                to="organisations.organisation",
                verbose_name="Organisation",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="groups_info", to="organisations.employee"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="members_info", to="organisations.group"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="groups_managers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups_members",
                through="organisations.Member",
                to="organisations.employee",
                verbose_name="Band members",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="organisations.organisation",
                verbose_name="Organisations",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_info",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="employees", to="organisations.position"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisations_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offer",
            unique_together={("organisation", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("group", "employee")},
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("organisation", "user")},
        ),
    ]
